## DSAN 6000 Homework 6B: Programmatic Athena Queries

In [2]:
import pandas as pd

In [4]:
test_df = pd.read_csv('test.csv.gz', delimiter='\t')
test_df

          latitude  longitude  population
0        13.824306  44.245972    2.346815
1        13.777917  44.240694    2.346815
2        13.791250  44.186250    2.346815
3        13.793750  44.184028    2.346815
4        13.825417  44.210972    2.346815
...            ...        ...         ...
1416150  14.296806  43.346806    2.144343
1416151  14.297639  43.297083    2.144343
1416152  14.229306  43.383472    2.144343
1416153  14.254028  43.364583    2.144343
1416154  14.277639  43.312917    2.144343

[1416155 rows x 3 columns]

In [6]:
total_pop = test_df['population'].sum()
total_pop

np.float64(4005339.4516194)

In [7]:
total_pop / 1_000_000

np.float64(4.0053394516194)

In [8]:
import boto3

In [9]:
s3 = boto3.client('s3')

In [16]:
paginator = s3.get_paginator('list_objects')
result = paginator.paginate(Bucket='dataforgood-fb-data', Prefix='csv/', Delimiter='/')
for prefix in result.search('CommonPrefixes'):
    print(prefix.get('Prefix'))

csv/month=2019-06/

In [17]:
paginator = s3.get_paginator('list_objects')
result = paginator.paginate(Bucket='dataforgood-fb-data', Prefix='csv/month=2019-06/', Delimiter='/')
for prefix in result.search('CommonPrefixes'):
    print(prefix.get('Prefix'))

csv/month=2019-06/country=NAM/
csv/month=2019-06/country=NCL/
csv/month=2019-06/country=NER/
csv/month=2019-06/country=NGA/
csv/month=2019-06/country=NIC/
csv/month=2019-06/country=NLD/
csv/month=2019-06/country=NPL/
csv/month=2019-06/country=NRU/
csv/month=2019-06/country=OMN/
csv/month=2019-06/country=PAN/
csv/month=2019-06/country=PCN/
csv/month=2019-06/country=PER/
csv/month=2019-06/country=PHL/
csv/month=2019-06/country=PLW/
csv/month=2019-06/country=PNG/
csv/month=2019-06/country=POL/
csv/month=2019-06/country=PRI/
csv/month=2019-06/country=PRT/
csv/month=2019-06/country=PRY/
csv/month=2019-06/country=PSE/
csv/month=2019-06/country=PYF/
csv/month=2019-06/country=QAT/
csv/month=2019-06/country=REU/
csv/month=2019-06/country=ROU/
csv/month=2019-06/country=RWA/
csv/month=2019-06/country=SAU/
csv/month=2019-06/country=SDN/
csv/month=2019-06/country=SEN/
csv/month=2019-06/country=SGP/
csv/month=2019-06/country=SLB/
csv/month=2019-06/country=SLE/
csv/month=2019-06/country=SLV/
csv/month=2019-06/country=SMR/
csv/month=2019-06/country=SOM/
csv/month=2019-06/country=SRB/
csv/month=2019-06/country=SSD/
csv/month=2019-06/country=STP/
csv/month=2019-06/country=SUR/
csv/month=2019-06/country=SVK/
csv/month=2019-06/country=SVN/
csv/month=2019-06/country=SWZ/
csv/month=2019-06/country=SYC/
csv/month=2019-06/country=SYR/
csv/month=2019-06/country=TCA/
csv/month=2019-06/country=TCD/
csv/month=2019-06/country=TGO/
csv/month=2019-06/country=THA/
csv/month=2019-06/country=TLS/
csv/month=2019-06/country=TON/
csv/month=2019-06/country=TTO/
csv/month=2019-06/country=TUN/
csv/month=2019-06/country=TUR/
csv/month=2019-06/country=TUV/
csv/month=2019-06/country=TWN/
csv/month=2019-06/country=TZA/
csv/month=2019-06/country=UGA/
csv/month=2019-06/country=UKR/
csv/month=2019-06/country=URY/
csv/month=2019-06/country=USA/
csv/month=2019-06/country=VCT/
csv/month=2019-06/country=VEN/
csv/month=2019-06/country=VGB/
csv/month=2019-06/country=VIR/
csv/month=2019-06/country=VNM/
csv/month=2019-06/country=VUT/
csv/month=2019-06/country=WLF/
csv/month=2019-06/country=WSM/
csv/month=2019-06/country=YEM/
csv/month=2019-06/country=ZAF/
csv/month=2019-06/country=ZMB/
csv/month=2019-06/country=ZWE/

In [18]:
import pandas as pd

In [19]:
pop_df = pd.read_csv('pop.tsv', delimiter='\t')

In [22]:
pop_df.tail()

,gadm_id,gadm_name,iso2,polygon_geojson,population,men,women,women_of_reproductive_age_15_49,children_under_five,youth_15_24,elderly_60_plus,ds
39422,DZA.45.25_1,Sidi Semiane,DZ,"{""type"":""MultiPolygon"",""coordinates"":[[[[2.108...",2782.856739,1437.967612,1344.889127,837.940114,246.419717,764.925393,199.796751,2022-02-05
39423,DZA.11.24_1,Ouled Brahem,DZ,"{""type"":""MultiPolygon"",""coordinates"":[[[[5.134...",8474.449629,4335.164225,4139.285404,2427.258837,835.146174,2239.304477,503.289960,2022-02-05
39424,JPN.12.28_1,Fukagawa,JP,"{""type"":""MultiPolygon"",""coordinates"":[[[[142.1...",22268.406371,10318.506418,11949.899954,3690.189866,609.964568,1675.065847,9669.860492,2022-02-05
39425,NOR.17.8_1,Ibestad,NO,"{""type"":""MultiPolygon"",""coordinates"":[[[[17.13...",1154.724166,587.534072,567.190094,177.763659,30.561117,146.187883,432.035015,2022-02-05
39426,BDI.1.1_1,Bubanza,BI,"{""type"":""MultiPolygon"",""coordinates"":[[[[29.37...",95443.125680,47975.916637,47467.209043,21219.091429,18007.795438,18671.630604,3515.329663,2022-02-05

In [21]:
pop_df['iso2'].value_counts()

iso2
BR    5500
US    3138
RO    2939
MX    1850
JP    1809
      ...
DJ      11
BE      11
MO       8
ST       7
WF       5
Name: count, Length: 145, dtype: int64